patterns_list = [
        "[Intro], [Name] is a [Gender] [Religion] name meaning '[Meaning]'. It symbolizes [Symbolism].",
        "[Intro], [Name] is a [Gender] [Religion] name associated with [Meaning]. It represents [Symbolism].",
        "[Name] is a popular [Gender] name in [Religion] culture, signifying [Meaning]. It embodies [Symbolism].",
        "[Name], commonly used in [Religion], is a meaningful [Gender] name denoting [Meaning]. It reflects [Symbolism].",
        "In the context of [Religion], [Name] is a beloved choice for [Gender]s. Its meaning, '[Meaning],' conveys [Symbolism].",
        "[Intro], [Name] is a name deeply rooted in [Religion], carrying the significance of [Meaning]. It exemplifies [Symbolism].",
        "[Name], a [Religion] name, holds a special place for [Gender]s. Its meaning, '[Meaning],' symbolizes [Symbolism].",
        "[Name], derived from [Religion], is a cherished [Gender] name with the profound meaning of [Meaning]. It embodies [Symbolism].",
        "In [Religion], [Name] is a name chosen for [Gender]s, representing [Meaning]. It signifies [Symbolism].",
        "[Name], a [Gender] name associated with [Religion], carries the beautiful meaning of [Meaning]. It encompasses [Symbolism].",
        "The name [Name] is commonly chosen for [Gender]s in [Religion]. Its meaning, '[Meaning],' reflects [Symbolism].",
        "In [Religion], the name [Name] signifies [Meaning]. It is a popular choice for [Gender]s, symbolizing [Symbolism].",
        "Looking for a unique [Gender] name in [Religion]? Consider [Name], which means '[Meaning]' and embodies [Symbolism].",
        "Searching for a meaningful [Gender] name? Look no further than [Name] in [Religion], representing [Meaning] and [Symbolism].",
        "[Name], a name rooted in [Religion], carries the essence of [Meaning]. It is a cherished choice for [Gender]s, symbolizing [Symbolism].",
        "Need a name with a significant meaning? [Name] in [Religion] is a perfect choice for [Gender]s, representing [Meaning] and [Symbolism].",
        "[Name] is a beloved [Religion] name for [Gender]s, symbolizing [Symbolism] and carrying the profound meaning of [Meaning].",
        "When it comes to [Gender] names in [Religion], [Name] stands out with its beautiful meaning of '[Meaning]' and the symbolism of [Symbolism].",
        "Choose [Name] for your [Gender] in [Religion] to embrace the deep meaning of '[Meaning]' and the symbolism of [Symbolism].",
        "Looking for a [Religion] name with a touch of sweetness? [Name], meaning '[Meaning],' represents [Symbolism] for [Gender]s.",
        "[Name] is a [Gender] name derived from [Religion], carrying the meaning of [Meaning]. It symbolizes [Symbolism].",
        "In [Religion], [Name] is a popular choice for [Gender]s due to its profound meaning of [Meaning]. It embodies [Symbolism].",
        "Consider the name [Name] for your [Gender] in [Religion]. Its meaning, '[Meaning],' reflects the essence of [Symbolism].",
        "[Name], a meaningful [Religion] name for [Gender]s, encapsulates the beauty of [Meaning] and represents [Symbolism].",
        "Looking for a [Religion] name? [Name] is a beloved choice for [Gender]s, signifying [Meaning] and embodying [Symbolism].",
        "The name [Name] in [Religion] holds the significance of [Meaning]. It is a perfect fit for [Gender]s and symbolizes [Symbolism].",
        "[Name] is a unique [Gender] name associated with [Religion], representing [Meaning] and carrying the symbolism of [Symbolism].",
        "Embrace the meaningfulness of [Name], a [Religion] name for [Gender]s. Its essence of [Meaning] reflects [Symbolism].",
        "Discover the beauty of [Name], a name commonly used in [Religion]. It carries the profound meaning of [Meaning] and symbolizes [Symbolism].",
        "[Name] is a cherished [Gender] name in [Religion], signifying [Meaning] and capturing the essence of [Symbolism].",
        "[Name] is a name of [Religion] origin, often chosen for [Gender]s. Its meaning, '[Meaning],' conveys the symbolism of [Symbolism].",
        "In [Religion], the name [Name] represents the essence of [Meaning]. It is a beloved choice for [Gender]s, symbolizing [Symbolism].",
        "Searching for a significant [Gender] name? [Name] in [Religion] holds the deep meaning of [Meaning] and the symbolism of [Symbolism].",
        "[Name], derived from [Religion], carries the essence of [Meaning]. It is a unique choice for [Gender]s, symbolizing [Symbolism].",
        "Looking for a [Religion] name? Consider [Name] for your [Gender], as it embodies the meaning of [Meaning] and represents [Symbolism].",
        "The name [Name], rooted in [Religion], represents the essence of [Meaning]. It is a cherished choice for [Gender]s, symbolizing [Symbolism].",
        "Seeking a meaningful [Religion] name? [Name], with its beautiful meaning of [Meaning], captures the essence of [Symbolism] for [Gender]s.",
        "Choose [Name] as a [Gender] name in [Religion] to embrace the deep meaning of [Meaning] and the symbolism of [Symbolism].",
        "[Name], a [Religion] name, is associated with [Meaning] and embodies [Symbolism]. It is a perfect fit for [Gender]s.",
        "In [Religion], [Name] is a popular choice for [Gender]s. Its meaning, '[Meaning],' reflects [Symbolism] and carries a profound significance."
    ]


qualities = {
    "A": ["Adaptable", "Adventurous", "Affable", "Affectionate", "Ambitious", "Amiable", "Assertive", "Attentive", "Authentic", "Avant-garde", "Avid", "Artistic", "Astute", "Athletic", "Auspicious", "Aesthetic", "Altruistic", "Able", "Appreciative", "Amusing"],
    "B": ["Bold", "Brave", "Bright", "Brilliant", "Benevolent", "Blissful", "Bubbly", "Boundless", "Balanced", "Beautiful", "Beloved", "Bountiful", "Brainy", "Brawny", "Blithe", "Breathtaking", "Broad-minded", "Businesslike", "Busy", "Boisterous"],
    "C": ["Calm", "Capable", "Caring", "Candid", "Clever", "Compassionate", "Confident", "Considerate", "Creative", "Curious", "Charming", "Cheerful", "Coherent", "Comical", "Consistent", "Courageous", "Courteous", "Crisp", "Cultured", "Cunning"],
    "D": ["Daring", "Dazzling", "Debonair", "Decisive", "Delightful", "Dependable", "Determined", "Devoted", "Dignified", "Discerning", "Disciplined", "Discreet", "Dynamic", "Distinctive", "Dreamy", "Driven", "Dutiful", "Dazzling", "Decent", "Down-to-earth"],
    "E": ["Eager", "Easygoing", "Eccentric", "Educated", "Efficient", "Elegant", "Eloquent", "Empathetic", "Energetic", "Enthusiastic", "Entrepreneurial", "Equal", "Ethical", "Excellent", "Exciting", "Expressive", "Extraordinary", "Exuberant", "Easy to talk to", "Effervescent"],
    "F": ["Fabulous", "Fair", "Fantastic", "Fearless", "Fierce", "Friendly", "Focused", "Forgiving", "Funny", "Free-spirited", "Fascinating", "Fervent", "Fiery", "Fitting", "Flawless", "Flowing", "Fluent", "Fluffy", "Forgiving", "Frank"],
    "G": ["Generous", "Gentle", "Genuine", "Glamorous", "Glowing", "Graceful", "Gracious", "Grandiose", "Great-hearted", "Grounded", "Growing", "Guiding", "Gutsy", "Good", "Good-natured", "Gregarious", "Guarded", "Goal-oriented", "Gleeful", "Grateful"],
    "H": ["Happy", "Hard-working", "Harmonious", "Healthy", "Heartfelt", "Hearty", "Healing", "Helpful", "Honest", "Honorable", "Hopeful", "Humble", "Humorous", "Hypnotic", "Hospitable", "Hardy", "Handsome", "High-spirited", "High-reaching", "Holistic"],
    "I": ["Idealistic", "Imaginative", "Impartial", "Impressive", "Industrious", "Innovative", "Inquisitive", "Insightful", "Intelligent", "Intense", "Intrepid", "Inventive", "Irresistible", "Inspiring", "Influential", "Independent", "Inventive", "Inquisitive", "Inclusive", "Iconic"],
    "J": ["Jolly", "Joyful", "Jovial", "Jubilant", "Judicious", "Just", "Jazzy", "Jaunty", "Jocular", "Jittery", "Jumpy", "Jitterbug", "Jitterbugging", "Jambalaya", "Jagged", "Jaded", "Jamming", "Jaunting", "Jubilating", "Juking"],
    "K": ["Kind", "Keen", "Knowledgeable", "Kaleidoscopic", "Kaput", "Keen-eyed", "Kooky", "Kosher", "Kissable", "Knockout", "Kittenish", "Knavish", "Kingly", "Knightly", "Knowable", "Kooky", "Kick-ass", "Kind-hearted", "Kooky-crazy", "Kaleidoscopic"],
    "L": ["Lively", "Loving", "Loyal", "Luminous", "Lucky", "Literate", "Logical", "Limitless", "Liberated", "Lyrical", "Legendary", "Leisurely", "Level-headed", "Light-hearted", "Loud", "Luxuriant", "Laid-back", "Lucky", "Loving-kindness", "Luscious"],
    "M": ["Motivated", "Magical", "Magnetic", "Majestic", "Masterful", "Mellow", "Memorable", "Merry", "Methodical", "Mindful", "Modest", "Mature", "Musical", "Magnificent", "Marvellous", "Meek", "Modern", "Merciful", "Majestic", "Motivational"],
    "N": ["Nurturing", "Natural", "Neat", "Nice", "Nimble", "Noble", "Nurtured", "Nifty", "Nimble-fingered", "Nirvanic", "Noble-minded", "Nondiscriminatory", "Non-judgmental", "Notable", "Noteworthy", "Numerical", "Nutritious", "Nautical", "Navigational", "Nimble-footed"],
    "O": ["Optimistic", "Organized", "Original", "Outgoing", "Open-minded", "Observant", "Objective", "Outstanding", "Overwhelming", "Overjoyed", "Over the moon", "Overpowering", "Obedient", "Olympic", "On-the-ball", "On-target", "One-of-a-kind", "Out-of-this-world", "Outspoken", "Overflowing"],
    "P": ["Passionate", "Patient", "Persistent", "Positive", "Playful", "Polite", "Powerful", "Practical", "Precise", "Prepared", "Productive", "Professional", "Proud", "Peaceful", "Pleasant", "Precious", "Prompt", "Prominent", "Praiseworthy", "Proactive"],
    "Q": ["Quick-witted", "Quiet", "Quirky", "Quixotic", "Quaint", "Qualified", "Quantifiable", "Quiescent", "Quality-minded", "Queenly", "Questioning", "Quick-thinking", "Quick-tempered", "Quarrelsome", "Quotable", "Quavered", "Quarantine", "Quantum", "Quivering", "Quellable"],
    "R": ["Resilient", "Resourceful", "Respectful", "Responsible", "Romantic", "Reliable", "Radiant", "Rational", "Reasonable", "Refreshing", "Rejoicing", "Relaxed", "Receptive", "Renowned", "Robust", "Rhapsodic", "Ravishing", "Razor-sharp", "Reassuring", "Rhapsodizing"],
    "S": ["Sincere", "Sensitive", "Strong", "Stylish", "Supportive", "Smart", "Spirited", "Sociable", "Sophisticated", "Successful", "Serene", "Stimulating", "Self-assured", "Selfless", "Serendipitous", "Sumptuous", "Sustainable", "Sagacious", "Stupendous", "Sassy"],
    "T": ["Trustworthy", "Talented", "Tactful", "Tenacious", "Thoughtful", "Thrifty", "Tolerant", "Transparent", "Transformative", "Truthful", "Trendy", "Tireless", "Triumphant", "Terrific", "Terrifying", "Thrilled", "Tantalizing", "Teeming", "Tempting", "Tender-hearted"],
    "U": ["Understanding", "Unflappable", "Unpretentious", "Unwavering", "Upbeat", "Unbiased", "Uncommon", "Unconventional", "Uninhibited", "Unique", "Ultimate", "Unstoppable", "Upstanding", "Uplifting", "Unselfish", "Urgent", "Undaunted", "Unforgettable", "Unfailing", "Ubiquitous"],
    "V": ["Vibrant", "Versatile", "Valiant", "Valuable", "Vigilant", "Virtuous", "Visionary", "Vivacious", "Venturesome", "Valedictory", "Venerated", "Voluminous", "Voluptuous", "Vivifying", "Vigorous", "Vexatious", "Vigilante", "Vocalizing", "Venerated", "Venerable"],
    "W": ["Wise", "Witty", "Warm-hearted", "Well-informed", "Well-rounded", "Willing", "Wondrous", "Winning", "Wealthy", "Wholesome", "Welcoming", "Wonder-struck", "Workaholic", "World-class", "Worshipful", "Wistful", "Windswept", "Wondrous", "Whimsical", "Wavy-haired"],
    "X": ["Xenial", "Xenodochial", "Xenolithic", "Xeric", "Xylographic", "Xanthic", "Xenogenic", "Xerothermic", "Xerophytic", "Xylophagous", "Xenophobic", "Xyloid", "Xenotropic", "Xylophilous", "Xanthochroic", "Xenotropic", "Xenotransplantable", "Xerophilous", "Xylotomous", "Xenogamous"],
    "Y": ["Youthful", "Yearning", "Yielding", "Yummy", "Yare", "Yogic", "Yarely", "Yampy", "Yester", "Yearlong", "Yeasty", "Yippee", "Yummylicious", "Yin", "Yarely", "Yellowish", "Yellow-bellied", "Yawning", "Yarely", "Youngish"],
    "Z": ["Zealous", "Zestful", "Zippy", "Zany", "Zippy", "Zonal", "Zillionaire", "Zappy", "Zygodactyl", "Zealotic", "Zeitgeisty", "Zestiness", "Zestily", "Zigzagging", "Zesty", "Zooarchaeological", "Zoomorphic", "Zoophoric", "Zoophilous", "Zoophagous"]
}


sorry= [
    "I'm sorry, but I don't have any information on that topic",
    "Unfortunately, I don't have any data related to what you're asking for.",
    "I'm afraid I don't understand what you're looking for.",
    "I'm sorry, but I don't have any relevant data to provide.",
    "I'm unable to find any information that matches your request.",
    "I'm sorry, but I cannot assist you with that particular matter.",
    "I'm afraid I don't have the capability to answer that question.",
    "Unfortunately, I'm not able to provide you with a helpful response.",
    "I'm sorry, but I don't have any knowledge related to your inquiry.",
    "I'm unable to help you with that topic, as it is outside my area of expertise.",
    "I'm sorry, but I couldn't find any information related to your query.",
    "I'm sorry, but your query does not match any data in my system.",
    "I'm unable to find any relevant data based on your query.",
    "I'm sorry, but I don't have any data that matches your request.",
    "I'm afraid I couldn't understand your query. Could you please rephrase it?",
    "I'm sorry, but the information you're looking for is not available in my database.",
    "I'm unable to provide any information on that topic as it is outside my scope.",
    "I'm sorry, but I don't have any data that corresponds to your query.",
    "I'm afraid I cannot help you with that query as it is not within my area of expertise."
]

hello = [    "Hello! How can I assist you today?",    "Welcome back! What can I help you with?",    "Nice to see you again! What can I do for you today?",    "Hi there! How may I be of service?",    "Greetings! What brings you here today?",    "Welcome! I'm here to help. What do you need assistance with?",    "Hello, and welcome to [your company/brand]! How can I assist you?",    "Hey, great to have you here! What can I do to assist you today?",    "Hi, welcome to our chatbot! What can I help you with?",    "Good to see you! How may I be of assistance?",    "Hi! It's great to have you here. How can I assist you?",    "Welcome back! What can I help you with today?",    "Greetings! I'm here to help. What can I do for you?",    "Hello, and welcome to our chatbot. How may I be of assistance?",    "Nice to see you again! What can I help you with today?",    "Welcome to [your company/brand], how can I assist you?",    "Hi there! I'm here to help you with anything you need. What can I do for you?",    "Hello and welcome! How can I make your experience better?",    "Welcome to our chatbot! What can I help you with today?",    "Hi, it's great to have you here! How can I assist you today?"]
